<a href="https://colab.research.google.com/github/sandeeep-prajapati/pytorch_Practice_Repo/blob/main/basics/besicsOfPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import torch
import torchvision
import torch.nn as nn
import torchvision.transforms as transforms
import numpy as np

In [2]:
x = torch.tensor(1.0,requires_grad = True)
w = torch.tensor(2.0,requires_grad = True)
b = torch.tensor(3.0,requires_grad = True)

In [3]:
y = w*x+b

In [4]:
y.backward()

In [5]:
print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


In [7]:
x = torch.randn(10,3)
y = torch.randn(10,2)
linear = nn.Linear(3,2)
print('W : ',linear.weight)
print('B : ',linear.bias)

W :  Parameter containing:
tensor([[ 0.1232, -0.4191,  0.3570],
        [-0.4218,  0.1456,  0.3915]], requires_grad=True)
B :  Parameter containing:
tensor([-0.2203,  0.3442], requires_grad=True)


In [16]:
criterion = nn.MSELoss()
pred = linear(x)
loss = criterion(pred,y)
loss.backward()
optimizer = torch.optim.SGD(linear.parameters(),lr = 0.001)

In [17]:
print('loss : ',loss.item())

loss :  1.6957963705062866


In [18]:
print('dL/dw : ',linear.weight.grad)
print('dL/dw : ', linear.bias.grad)

dL/dw :  tensor([[ 0.5561, -0.3657,  0.7030],
        [-1.8126,  0.8149,  1.6457]])
dL/dw :  tensor([0.4764, 1.2379])


In [19]:

optimizer.step()

In [20]:
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

loss after 1 step optimization:  1.6911262273788452


In [22]:
x = np.array([[1,2],[3,4]])
y = torch.from_numpy(x)
z = y.numpy()

In [23]:
print(z,y,x)

[[1 2]
 [3 4]] tensor([[1, 2],
        [3, 4]]) [[1 2]
 [3 4]]


In [27]:
train_dataset = torchvision.datasets.CIFAR10(root = './data',
                                            train = True,
                                            transform = transforms.ToTensor(),
                                            download = True)
image,label = train_dataset[0]
print(image.size())
print(label)

Files already downloaded and verified
torch.Size([3, 32, 32])
6


In [28]:
train_loader = torch.utils.data.DataLoader(dataset = train_dataset,
                                           batch_size = 64,
                                           shuffle = True)



In [30]:
for images, labels in train_loader:
  print(images)
  print(label)
  break

tensor([[[[0.2000, 0.2196, 0.2157,  ..., 0.2549, 0.2549, 0.2431],
          [0.2549, 0.2196, 0.2314,  ..., 0.2353, 0.2392, 0.2471],
          [0.2431, 0.2118, 0.2549,  ..., 0.2314, 0.2314, 0.2431],
          ...,
          [0.1804, 0.1529, 0.1608,  ..., 0.1725, 0.1843, 0.1882],
          [0.1765, 0.1922, 0.1843,  ..., 0.1843, 0.1961, 0.2157],
          [0.1765, 0.1647, 0.1647,  ..., 0.1922, 0.1882, 0.1961]],

         [[0.2941, 0.3137, 0.3098,  ..., 0.3647, 0.3647, 0.3529],
          [0.3451, 0.3059, 0.3216,  ..., 0.3451, 0.3451, 0.3529],
          [0.3333, 0.3020, 0.3490,  ..., 0.3412, 0.3373, 0.3490],
          ...,
          [0.2667, 0.2353, 0.2431,  ..., 0.2549, 0.2745, 0.2667],
          [0.2745, 0.2902, 0.2784,  ..., 0.2627, 0.2745, 0.2824],
          [0.2863, 0.2706, 0.2706,  ..., 0.2627, 0.2588, 0.2627]],

         [[0.1059, 0.1294, 0.1333,  ..., 0.1608, 0.1608, 0.1451],
          [0.1804, 0.1333, 0.1412,  ..., 0.1451, 0.1412, 0.1333],
          [0.1608, 0.1216, 0.1608,  ..., 0

In [31]:
# create your own customDataset loader as below
class CustomDataset(torch.utils.data.Dataset):
  def __init__(self):
    # initialize file paths or a list of fils names.
    pass
  def __getitem__(self,index):
    # 1. Read one data from file (e.g. using numpy.fromfile, PIL.Image.open).
    # 2. Preprocess the data (e.g. torchvision.Transform).
    # 3. Return a data pair (e.g. image and label).
    pass
  def __len__(self):
    # You should change 0 to the total size of your dataset.
    return 0

In [32]:
custom_dataset = CustomDataset()
train_loader = torch.utils.data.DataLoader(dataset = custom_dataset,
                                           batch_size = 64,
                                           shuffle = True)

ValueError: num_samples should be a positive integer value, but got num_samples=0

In [33]:
resnet = torchvision.models.resnet18(pretrained = True)
for param in resnet.parameters():
  param.requires_grad = False

resnet.fc = nn.Linear(resnet.fc.in_features,100)
images = torch.randn(64,3,224,224)
outputs = resnet(images)
print(outputs.size())

/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100%|██████████| 44.7M/44.7M [00:00<00:00, 105MB/s]


torch.Size([64, 100])


In [34]:
torch.save(resnet, 'model.ckpt')
model = torch.load('model.ckpt')


In [35]:
torch.save(resnet.state_dict(), 'params.ckpt')
resnet.load_state_dict(torch.load('params.ckpt'))

<All keys matched successfully>